version: '3.8'

services:
  mongodb:
    image: mongo:5.0
    container_name: Delivery_Management_mongodb
    ports:
      - "27300:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "example"
      MONGO_INITDB_DATABASE: "Delivery_Replication"
    volumes:
      - mongodata:/data/db
    restart: unless-stopped
    command: ["mongod", "--bind_ip_all"]
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 2G

volumes:
  mongodata:
